### ISSUE TITLE
After processing GetOwnedGames request and trying to access a single game field, its name is null.

### ISSUE THREAD

**Issue by ChuckHendersen** [lpradel/steam-web-api-java#19]
As per title. I can't seem to get the steam App name.
GetOwnedGamesRequest request =  SteamWebApiRequestFactory.createGetOwnedGamesRequest("/*YOURSTEAMID*/");
GetOwnedGames gog = SteamAPI.client.<GetOwnedGames>processRequest(request);
for(com.lukaspradel.steamapi.data.json.ownedgames.Game apiGame : gog.getResponse().getGames() ){
    System.out.println(apiGame.getName());
}

The output of this foreach loop is null :(
The appID field is fine though.

![image](https://user-images.githubusercontent.com/59712930/230800238-2bdb1f80-28f7-4896-adc1-093b7daa8de0.png)

**Comment by lpradel** [comment]
Hi Giovanni,

please see this answer in a similar issue:
https://github.com/lpradel/steam-web-api-java/issues/4#issuecomment-167119315

In short, do the following:
```
GetOwnedGamesRequest request = new GetOwnedGamesRequest.GetOwnedGamesRequestBuilder( "steam-id").includeAppInfo(true).buildRequest();
```

Or use the other factory method ` SteamWebApiRequestFactory.createGetOwnedGamesRequest(String steamId, boolean includeAppInfo, boolean includePlayedFreeGames, List<Integer> appIdsFilter)` which accepts `includeAppInfo`.

See [Steam API documentation](https://developer.valvesoftware.com/wiki/Steam_Web_API#Arguments_7) for `GetOwnedGames`

See also this SO comment explaining it:
https://stackoverflow.com/a/73028555/1055743

**Comment by ChuckHendersen** [comment]
Alright, thank you for the quick reply.
